# Numpy ndarrays

In [1]:
import numpy as np

In [2]:
# %timeit a = list(range(100001))
# %timeit b =  np.arange(100001)
a = list(range(101))
b =  np.arange(101)

In [3]:
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [4]:
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

How do we multiply every value by two?

In [5]:
for i in range(len(a)):
    a[i] *= 2
print(a)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


In [6]:
b * 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [7]:
b[2:] *= 2
b

array([  0,   1,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

## Experiments with using numpy with a character grid:

In [8]:
lines = ['appled',
         'nnigal',
         'dogsbe',
         'rshrei',
         'oxenyy',
         'ilwepq',
         'drehsm']

# method of "loading" these characters into array inspired by
# https://stackoverflow.com/questions/9476797/how-do-i-create-character-arrays-in-numpy

g = np.array(lines, dtype=np.unicode_)
grid = g.view('U1').reshape((g.size, -1))
print(grid)

[['a' 'p' 'p' 'l' 'e' 'd']
 ['n' 'n' 'i' 'g' 'a' 'l']
 ['d' 'o' 'g' 's' 'b' 'e']
 ['r' 's' 'h' 'r' 'e' 'i']
 ['o' 'x' 'e' 'n' 'y' 'y']
 ['i' 'l' 'w' 'e' 'p' 'q']
 ['d' 'r' 'e' 'h' 's' 'm']]


In [9]:
grid.shape  # Verify the dimensions of this array: (7 rows by 6 columns)

(7, 6)

# Extracting columns
When we have a list of lists, or similar 2-dimensional structures, we often need to extract something from COLUMNS. In regular Python structures such as a list of lists, this requires looping to do:

In [10]:
column_0 = []
for line in lines:
    column_0.append(line[0])
print(column_0)

['a', 'n', 'd', 'r', 'o', 'i', 'd']


## ndarray columns are better:
With Numpy ndarrays, our slicing features work MULTI-dimensionally.  
So we can extract a column easily (and very fast) like this:

In [11]:
print(grid[:, 0])  # vertical slice

['a' 'n' 'd' 'r' 'o' 'i' 'd']


In [12]:
# Numpy arrays are iterable. 
# So we can use string join to convert array into a single string:
''.join(grid[:, 0])  

'android'

In [13]:
''.join(grid[0, 0:5])  # with 2D slicing, pick 'apple' from the grid.

'apple'

# Searching a 2D array

In [14]:
# one way to search for a specific value in a specific row:
if ['e'] in grid[0]:
    print('found an e.')

found an e.


In [15]:
grid[0]

array(['a', 'p', 'p', 'l', 'e', 'd'], 
      dtype='<U1')

In [16]:
# This approach DOES NOT WORK to search for a sequence:
if ['a', 'p', 'p', 'l', 'e'] in list(grid[0]):
    print('found an apple.')

In [17]:
x = [ ['a', 'p', 'p', 'l', 'e'],
      ['p', 'o', 't','a','t','o']]
if ['a', 'p', 'p', 'l', 'e'] in x:
    print('found an apple.')

found an apple.


This next approach does work to find strings within a row or column, but for large grids it would likely be slow, because we're losing most efficiency advantages of the ndarray.  Imagine if this grid contained 1000 rows and columns:

In [18]:
for row in range(grid.shape[0]):
    if 'oxen' in ''.join(grid[row]):
        print('found the oxen in row', row)

found the oxen in row 4


A different idea is to use the filtering features of ndarray to eliminate the rows that can't contain our search target.  In English vocabulary, the "x" in "oxen" is rare, so let's try filtering for "x":

In [19]:
grid == 'x'  # builds a matching ndarray of True/False on the condition

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

In [20]:
np.where(grid == 'x', grid, '') # Use the condition to extract all "x" values

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', 'x', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], 
      dtype='<U1')

From the above result, we know that if "oxen" exists in the grid at all, it must be located through index position 4,1.

# Clever counting
The numpy.count_nonzero() method works on True/False values! This is because like most other languages, zeros are considered False, and most other values are considered True.  

In [21]:
# See which columns have an 'x' value:
np.count_nonzero(grid == 'x', axis=0)

array([0, 1, 0, 0, 0, 0])

In [22]:
# See which rows have an 'x' value:
np.count_nonzero(grid == 'x', axis=1)

array([0, 0, 0, 0, 1, 0, 0])

In [23]:
columns = np.count_nonzero(grid == 'x', axis=0)
rows    = np.count_nonzero(grid == 'x', axis=1)

possible_columns = np.where(columns, grid, '')
print(possible_columns)
print()
possible_rows = np.transpose(np.where(rows, np.transpose(grid), ''))
print(possible_rows)

[['' 'p' '' '' '' '']
 ['' 'n' '' '' '' '']
 ['' 'o' '' '' '' '']
 ['' 's' '' '' '' '']
 ['' 'x' '' '' '' '']
 ['' 'l' '' '' '' '']
 ['' 'r' '' '' '' '']]

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['o' 'x' 'e' 'n' 'y' 'y']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [24]:
x_found = grid == 'x'
x_found

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

# Other searching approaches.
We could take a candidate word (like "oxen") and make sure that all its letters are in the grid somewhere.  If not, there's no point searching for it!

But if our grid contains all the letters in our language, this will be a waste of time to compute for each candidate word.

In [25]:
letters = np.unique(grid)  # get the unique members of the grid.
letters

array(['a', 'b', 'd', 'e', 'g', 'h', 'i', 'l', 'm', 'n', 'o', 'p', 'q',
       'r', 's', 'w', 'x', 'y'], 
      dtype='<U1')

In [26]:
np.in1d(['o','x','n','e'], letters).all()  # Are ALL the specified letters in the puzzle somewhere?

True

# What about searching diagonally? 

In [27]:
print(grid, '\n')
print(np.diagonal(grid))

[['a' 'p' 'p' 'l' 'e' 'd']
 ['n' 'n' 'i' 'g' 'a' 'l']
 ['d' 'o' 'g' 's' 'b' 'e']
 ['r' 's' 'h' 'r' 'e' 'i']
 ['o' 'x' 'e' 'n' 'y' 'y']
 ['i' 'l' 'w' 'e' 'p' 'q']
 ['d' 'r' 'e' 'h' 's' 'm']] 

['a' 'n' 'g' 'r' 'y' 'q']


In [28]:
print(np.diagonal(grid, 1))

['p' 'i' 's' 'e' 'y']


In [29]:
print(np.diagonal(grid, -1))

['n' 'o' 'h' 'n' 'p' 'm']


### So, using that technique, how do we get the other diagonals? (going from upper-right to lower-left)

In [30]:
flipped = np.fliplr(grid)  # We create a "flipped" copy of the array.
print(flipped)

[['d' 'e' 'l' 'p' 'p' 'a']
 ['l' 'a' 'g' 'i' 'n' 'n']
 ['e' 'b' 's' 'g' 'o' 'd']
 ['i' 'e' 'r' 'h' 's' 'r']
 ['y' 'y' 'n' 'e' 'x' 'o']
 ['q' 'p' 'e' 'w' 'l' 'i']
 ['m' 's' 'h' 'e' 'r' 'd']]


In [31]:
print(np.diagonal(flipped))

['d' 'a' 's' 'h' 'x' 'i']


In [32]:
%timeit flipped = np.fliplr(grid)  # We create a "flipped" copy of the array.


The slowest run took 15.36 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 854 ns per loop
